FROM openjdk:21-ea-24-oracle

WORKDIR /app

# Copia el JAR generado
COPY target/LabUsuarios-0.0.1-SNAPSHOT.jar app.jar

# Copia la carpeta del wallet Oracle
COPY wallet_ORACLE ./wallet_ORACLE

# Exponer puerto del microservicio
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
