FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

# Imagen final
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copiar el jar
COPY --from=build /build/target/LabUsuarios-0.0.1-SNAPSHOT.jar app.jar

# Crear carpeta donde Docker montará el wallet
RUN mkdir -p /app/wallet_ORACLE

# Variable necesaria para Oracle Wallet
ENV TNS_ADMIN=/app/wallet_ORACLE

EXPOSE 8080
ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
