version: '1'
services:
  micro2:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@a8l4bsvsef6piv46_medium?TNS_ADMIN=./wallet_ORACLE
      - spring.datasource.username=${ORACLE_USER}
      - spring.datasource.password=${ORACLE_PASS}
    restart: "always"